SecureZen/SecureZen/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from secure.views import index  # Import the index view
from django.conf.urls import handler404
from secure.views import custom_404

handler404 = 'secure.views.custom_404'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="home"),  # Directly route the root URL to the index view
    path("", include(('secure.urls', 'secure'), namespace='secure')),  # General site routes
    path("api/v1/scanner/", include(('scanner.urls', 'scanner_api'), namespace='scanner_api')),  # API access
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SecureZen/secure/urls.py
# secure/urls.py
from django.urls import path
from .views import CustomLoginView, index, about, contact, registration, login, profile, logout_view


app_name = 'secure'

urlpatterns = [
    path('', index, name='index'),  # Adjusted for the root URL
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('registration/', registration, name='registration'),
    path('login/', login, name='login'),  # Keep this if it's a different view or remove if using CustomLoginView for the same purpose
    path('profile/', profile, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('accounts/login/', CustomLoginView.as_view(), name='custom_login'),  # Ensure CustomLoginView is imported
    # Removed duplicate 'accounts/profile/' if it's not needed or adjust as necessary
]

SecureZen/secure/forms.py
# Import necessary modules and classes from Django
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User

# Custom form for user login, inherits from AuthenticationForm
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs={"autofocus": True, 'class': 'form-control', 'placeholder': 'Enter your username'})
    )
    # Customize the password field
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", 'class': 'form-control', 'placeholder': 'Enter your password'})
    )

    # Meta class to associate the form with the User model
    class Meta:
        model = User
        # Specify the fields to be included in the form
        fields = ['username', 'password']

# Custom form for user registration, inherits from Django's built-in UserCreationForm
class UserRegistrationForm(UserCreationForm):
    # Customize additional fields for user registration
    first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter your first name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter your last name"}))
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Choose a username"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "Enter your email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Enter a password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Confirm your password"}))

    # Meta class to associate the form with the User model
    class Meta:
        model = User
        # Specify the fields to be included in the form
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

# Custom form for user profile editing, inherits from Django's built-in UserChangeForm
class ProfileForm(UserChangeForm):
    # Add an image field for the user's profile picture
    image = forms.ImageField(widget=forms.FileInput(attrs={"class": "form-control mt-3"}), required=False)
    # Customize additional fields for profile editing
    first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter your first name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Enter your last name"}))
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Choose a username"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "Enter your email"}))

    # Meta class to associate the form with the User model
    class Meta:
        model = User
        # Specify the fields to be included in the form
        fields = ("image", "first_name", "last_name", "username", "email")

SecureZen/templates/users/login.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <!-- Display Messages -->
        {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">{% trans 'Login' %}</h2>
                <form action="{% url 'secure:login' %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value={{request.GET.next}}>
                    {% endif %}

                    <!-- Username Input -->
                    <div class="mb-3">
                        <label for="id_username" class="form-label">{% trans 'Username' %}</label>
                        <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}"
                               name="username" id="id_username"
                               placeholder="{% trans 'Enter your username' %}"
                               required>
                        {% for error in form.username.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>

                    <!-- Password Input -->
                    <div class="mb-3">
                        <label for="id_password" class="form-label">{% trans 'Password' %}</label>
                        <input type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}" 
                               name="password" id="id_password"
                               placeholder="{% trans 'Enter your password' %}" required>
                        {% for error in form.password.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    {% comment %} {% for item in form %}
                    <div class="mb-3">
                        <label for="{{ item.id_for_label }}" class="form-label">{{ item.label }}</label>
                        {{item}}
                    </div>
                    {% endfor %} {% endcomment %}


                    {% comment %} <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                        {{form.username}}
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        {{ form.password }}
                    </div> {% endcomment %}

                    
                    {% comment %} <div class="mb-3">
                        <label for="username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль" required>
                    </div> {%endcomment%}
                    <!-- Submit Button -->
                    <button type="submit" class="btn btn-dark btn-block">{% trans 'Login' %}</button>
                </form>

                <!-- Additional Links -->
                <div class="mt-3">
                    <a href="#">{% trans 'Forgot password?' %}</a> | 
                    <a href="{% url 'secure:registration' %}">{% trans 'Create an account' %}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

SecureZen/templates/users/profile.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="container mt-5  pb-5">
        <!-- User Profile Section -->
        <div class="row justify-content-center">
            <div class="col-md-5 bg-white p-4 mb-4 rounded custom-shadow">
                <h3 class="text-center mb-4">{% trans 'User Profile'%}</h3>
                <form action="{% url "secure:profile" %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3 text-center">
                        {% if user.image %}
                            <img src="{{ user.image.url }}" alt="{% trans 'User Avatar' %}" class="img-fluid rounded-circle" style="max-width: 150px;">
                        {% else %}
                            <img src="{% static "deps/images/1.png" %}" alt="{% trans 'User Avatar' %}" class="img-fluid rounded-circle" style="max-width: 150px;">
                        {% endif %}
                        <input type="file" class="form-control mt-3" id="id_image" name='image' accept="image/*" placeholder="Choose your avatar">
                        {% if form.image.errors %}
                            <div class="alert alert-danger">{{ form.image.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_first_name" class="form-label">{% trans 'First Name' %}* </label>
                        <input type="text" class="form-control" id="id_first_name"
                            name="first_name"
                            placeholder="{% trans 'Enter your first name' %}"
                            value="{{ form.first_name.value }}"
                            required>
                            {% if form.first_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_last_name" class="form-label">{% trans 'Last Name' %}*</label>
                        <input type="text" class="form-control" id="id_last_name"
                            name="last_name"
                            placeholder="{% trans 'Enter your last name' %}"
                            value="{{ form.last_name.value }}"
                            required>
                            {% if form.last_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_username" class="form-label">{% trans 'Username' %}*</label>
                        <input type="text" class="form-control" id="id_username"
                            name="username"
                            placeholder="{% trans 'Enter your username' %}"
                            value="{{ form.username.value }}"
                            required>
                            {% if form.username.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_email" class="form-label">{% trans 'Email' %}*</label>
                        <input type="email" class="form-control" id="id_email"
                            name="email"
                            placeholder="{% trans 'Enter your email (e.g., youremail@example.com)' %}"
                            value="{{ form.email.value }}"
                            required>
                            {% if form.email.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                            {% endif %}
                    </div>
                    <!-- Additional profile fields -->
                    <div class="text-center mt-3">
                        <button type="submit" class="btn btn-dark">{% trans 'Save Changes' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

SecureZen/templates/users/registration.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="container mt-5 pb-5 mb-5">
        <!-- User Profile Section -->
        <div class="row justify-content-center">
            <div class="col-md-5 bg-white p-4 mb-4 rounded custom-shadow" style="margin-bottom: 20px;">
                <h3 class="text-center mb-4">{% trans 'Registration'%}</h3>
                <form action="{% url "secure:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3 text-center">
                        {% if user.image %}
                            <img src="{{ user.image.url }}" alt="{% trans 'User Avatar' %}" class="img-fluid rounded-circle" style="max-width: 150px;">
                        {% else %}
                            <img src="{% static "deps/images/1.png" %}" alt="{% trans 'User Avatar' %}" class="img-fluid rounded-circle" style="max-width: 150px;">
                        {% endif %}
                        <input type="file" class="form-control mt-3" id="id_image" name='image' accept="image/*">
                        {% if form.image.errors %}
                            <div class="alert alert-danger">{{ form.image.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_first_name" class="form-label">{% trans 'First Name' %}* </label>
                        <input type="text" class="form-control" id="id_first_name"
                            name="first_name"
                            placeholder="{% trans 'Enter your first name' %}"
                            value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" required>
                            {% if form.first_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_last_name" class="form-label">{% trans 'Last Name' %}*</label>
                        <input type="text" class="form-control" id="id_last_name"
                            name="last_name"
                            placeholder="{% trans 'Enter your last name' %}" 
                            value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" required>
                            {% if form.last_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_username" class="form-label">{% trans 'Username' %}*</label>
                        <input type="text" class="form-control" id="id_username"
                            name="username"
                            placeholder="{% trans 'Enter your username' %}" 
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required>
                            {% if form.username.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_email" class="form-label">{% trans 'Email' %}*</label>
                        <input type="email" class="form-control" id="id_email"
                            name="email"
                            placeholder="{% trans 'Enter your email (e.g., youremail@example.com)' %}" 
                            value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required>
                            {% if form.email.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_password1" class="form-label">{% trans 'Password'%}*</label>
                        <input type="password" class="form-control" id="id_password1"
                            value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                            name="password1" 
                            placeholder="{% trans 'Enter your password'%}" required>
                            {% if form.password1.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_password2" class="form-label">{% trans 'Confirm your password'%}*</label>
                        <input type="password" class="form-control" id="id_password2"
                            value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                            name="password2"
                            placeholder="{% trans 'Confirm your password'%}" required>
                            {% if form.password2.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                            {% endif %}
                    </div>
                    <div class="text-center mt-3">
                      <button type="submit"
                      class="btn btn-dark btn-block">{% trans 'Register'%}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}