SecureZen/SecureZen/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from secure.views import index  # Import the index view
from django.conf.urls import handler404
from secure.views import custom_404

handler404 = 'secure.views.custom_404'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="home"),  # Directly route the root URL to the index view
    path("", include(('secure.urls', 'secure'), namespace='secure')),  # General site routes
    path("api/v1/scanner/", include(('scanner.urls', 'scanner_api'), namespace='scanner_api')),  # API access
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SecureZen/scanner/urls.py
from django.urls import path
from . import views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

app_name = 'scanner'

schema_view = get_schema_view(
    openapi.Info(
        title='Virustotal API',
        default_version='v2',
        description='API for security',
        terms_of_service="https://www.virustotal.com/vtapi/v2/file/report?apikey={apikey}&resource={resource}",
        # contact=openapi.Contact(email="contact@example.com"),  # Specify a contact email if available
        # license=openapi.License(name="BSD License"),  # Specify a license name if applicable
    ),
    public=True,
    permission_classes=()
)

urlpatterns = [
    path('openapi/', schema_view.without_ui(cache_timeout=0), name='schema-openapi'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc-ui'),
    path('upload/', views.upload_file, name='upload'),
    path('scan-url/', views.scan_url, name='scan-url'),
    path('user_urls/<str:username>/', views.user_urls, name='user_urls'),
    path('user_files/<str:username>/', views.user_files, name='user_files'),
]

SecureZen/secure/urls.py
# secure/urls.py
from django.urls import path
from .views import CustomLoginView, index, about, contact, registration, login, profile, logout_view


app_name = 'secure'

urlpatterns = [
    path('', index, name='index'),  # Adjusted for the root URL
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('registration/', registration, name='registration'),
    path('login/', login, name='login'),  # Keep this if it's a different view or remove if using CustomLoginView for the same purpose
    path('profile/', profile, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('accounts/login/', CustomLoginView.as_view(), name='custom_login'),  # Ensure CustomLoginView is imported
    # Removed duplicate 'accounts/profile/' if it's not needed or adjust as necessary
]

SecureZen/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
    <!-- Your custom styles can go here if not in a separate CSS file -->
{% endblock %}

{% block content %}
    <div class="container mt-4 pt-2 mb-5">
        <h3 class="text-left text-white"><strong>{{ title }}</strong></h3>
        <h4 class="text-left text-white"><strong>{{ content |linebreaks }}</strong></h4>
    </div>
{% endblock %}

SecureZen/templates/main/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="{% get_current_language as LANGUAGE_CODE %}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    
    {% block css %}
        <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
    {% endblock %}

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'deps/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'deps/favicon/site.webmanifest' %}">
    <title>{% block title %}{% trans 'Home' %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'secure:index' %}">{% trans "Home" %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'secure:about' %}">{% trans "About Us" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'secure:contact' %}">{% trans "Contact Information" %}</a>
                        </li>
                        <!-- Additional links can be added here -->
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'secure:login' %}">{% trans "Log in" %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'secure:registration' %}">{% trans "Registration" %}</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                   {% trans 'My Profile' %}
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item text-white" href="{% url 'secure:profile' %}">{% trans 'Personal Account' %}</a></li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item text-white" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
                                    {% endif %}
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item text-white" href="{% url 'secure:logout' %}">{% trans 'Log Out' %}</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block content1 %}
        <!-- This block will be overridden by child templates -->
    {% endblock %}
    {% if user.is_authenticated %}
        {% if request.path == '/' %}
            <div class="container mt-4">
                <div class="row">
                    <div class="col">
                        <!-- Button to go to Scan URL page -->
                        <a href="{% url 'scanner:scan-url' %}" class="btn btn-primary text-white">
                            {% trans 'Scan URL' %}
                        </a>
                        <a href="{% url 'scanner:user_urls' username=user.username %}"class="btn btn-secondary text-white">
                            {% trans 'URLs History' %}
                        </a>
                    </div>
                    <div class="col">
                        <!-- Button to go to Upload page -->
                        <a href="{% url 'scanner:upload' %}" class="btn btn-primary text-white">
                            {% trans 'File Upload' %}
                        </a>
                        <a href="{% url 'scanner:user_files' username=user.username %}"class="btn btn-secondary text-white">
                            {% trans 'Files History' %}
                        </a>
                    </div>
                </div>
            </div>
        {% endif %}

    {% else %}
        {% if request.path == '/' %}
            <div class="container mt-4">
                <div class="row">
                    <div class="col">
                        <!-- Button to go to Scan URL page -->
                        <a href="{% url 'scanner:scan-url' %}" class="btn btn-primary text-white">
                            {% trans 'Scan URL' %}
                        </a>
                    </div>
                    <div class="col">
                        <!-- Button to go to Upload page -->
                        <a href="{% url 'scanner:upload' %}" class="btn btn-primary text-white">
                            {% trans 'File Upload' %}
                        </a>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endif %}  
    {% block content2 %}
        <!-- This block will be overridden by child templates -->
    {% endblock %}
    {% block content %}
    <!-- This block will be overridden by child templates -->
    {% endblock %}
    <footer class="py-3 bg-dark">
        <div class="container d-flex align-items-center justify-content-center">
            <img src="{% static "deps/images/1.png" %}" alt="{% trans 'Logo' %}" id="logo">
            <p class="m-0 text-center text-white">{% trans 'Copyright &copy; SecureZen Team' %}</p>
        </div>
    </footer>
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'deps/js/jquery-events.js' %}"></script>
    <script src="{% static 'deps/js/jquery-ajax.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'deps/js/loader.js' %}"></script>
</body>
</html>

SecureZen/templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
    <!-- Your custom styles can go here if not in a separate CSS file -->
{% endblock %}

{% block content %}
    <div class="container mt-4 pt-2">
        <h3 class="text-left text-white"><strong>{{ title }}</strong></h3>
        <h4 class="text-left text-white"><strong>{{ text_on_page |linebreaks }}</strong></h4>
    </div>
{% endblock %}

SecureZen/templates/main/error_404.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans '404 Error' %}
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'deps/css/error_404.css' %}">
{% endblock %}

{% block content %}
<section class="error-image">
    <div class="container">
      <div class="text text-white">
        <h1>{% trans 'Something went wrong'%}</h1>
        <p>{% trans 'Please check the URL for any typos'%}.</p>
        {% comment %} <div class="input-box">
          <input type="text" placeholder="{% trans 'Search...' %}">
          <button><i class="fa-solid fa-search"></i></button>
        </div> {% endcomment %}
        <ul class="menu">
          <li><a class="navbar-brand" href="{% url 'secure:index' %}">{% trans "Home" %}</a></li>
          {% comment %} <li><a class="navbar-brand" href="{% url 'scanner:scan-url' %}" >{% trans 'Go to Scan URL' %}</a></li>
          <li><a class="navbar-brand" href="{% url 'scanner:upload' %}" >{% trans 'Go to Upload' %}</a></li> {% endcomment %}
        </ul>
      </div>
      <div class="error-image">
          <img src="{% static 'deps/images/error_404.jpeg' %}" alt="{% trans 'Error' %}">
      </div>
    </div>
</section>
{% endblock %}

SecureZen/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
{% endblock %}

{% block content1 %}
    <div class="container mt-4 mb-4"> <!-- Added mb-5 for margin-bottom -->
        <h3 class="text-center text-white"><strong>{{ title }}</strong></h3>
    </div>
{% endblock %}

{% block content2 %}
    <div class="container mt-4 mb-5"> <!-- Added mb-5 for margin-bottom -->
        <img src="{% static "deps/images/1.png" %}" alt="{% trans 'Logo' %}" id="home_page_logo">
        <h4 class="text-center text-white"><strong>{{ content |linebreaks }}</strong></h4>
    </div>
{% endblock %}